package TodoListCreator;

/**
* TodoListCreator/CreatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TodoListCreator.idl
* Tuesday, May 8, 2018 3:46:17 PM CST
*/

public final class CreatorHolder implements org.omg.CORBA.portable.Streamable
{
  public TodoListCreator.Creator value = null;

  public CreatorHolder ()
  {
  }

  public CreatorHolder (TodoListCreator.Creator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TodoListCreator.CreatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TodoListCreator.CreatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TodoListCreator.CreatorHelper.type ();
  }

}
