package TodoListCreator;


/**
* TodoListCreator/CreatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TodoListCreator.idl
* Tuesday, May 8, 2018 3:46:17 PM CST
*/

public interface CreatorOperations 
{
  boolean login (String username, String password);
  boolean register (String username, String password);
} // interface CreatorOperations
