package TodoListCreator;


/**
* TodoListCreator/Creator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TodoListCreator.idl
* Tuesday, May 8, 2018 3:46:17 PM CST
*/

public interface Creator extends CreatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Creator
