package UserCreator;


/**
* UserCreator/CreatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UserCreator.idl
* Thursday, May 17, 2018 7:45:14 PM CST
*/

public interface CreatorOperations 
{
  boolean login (String username, String password);
  boolean register (String username, String password);
} // interface CreatorOperations
