package UserCreator;

/**
* UserCreator/CreatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UserCreator.idl
* Thursday, May 17, 2018 7:45:14 PM CST
*/

public final class CreatorHolder implements org.omg.CORBA.portable.Streamable
{
  public UserCreator.Creator value = null;

  public CreatorHolder ()
  {
  }

  public CreatorHolder (UserCreator.Creator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = UserCreator.CreatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    UserCreator.CreatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return UserCreator.CreatorHelper.type ();
  }

}
