package UserCreator;


/**
* UserCreator/Creator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UserCreator.idl
* Thursday, May 17, 2018 7:45:14 PM CST
*/

public interface Creator extends CreatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Creator
