package Users;


/**
* Users/TodoList.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Users.idl
* Tuesday, May 8, 2018 3:46:12 PM CST
*/

public interface TodoList extends TodoListOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TodoList
