package Users;

/**
* Users/TodoListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Users.idl
* Tuesday, May 8, 2018 3:46:12 PM CST
*/

public final class TodoListHolder implements org.omg.CORBA.portable.Streamable
{
  public Users.TodoList value = null;

  public TodoListHolder ()
  {
  }

  public TodoListHolder (Users.TodoList initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Users.TodoListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Users.TodoListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Users.TodoListHelper.type ();
  }

}
