package Users;


/**
* Users/TodoListOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Users.idl
* Tuesday, May 8, 2018 3:46:12 PM CST
*/

public interface TodoListOperations 
{
  boolean add (String startTime, String endTime, String description);
  String query (String startTime, String endTime);
  boolean delete (String key);
  boolean clear ();
  String show ();
} // interface TodoListOperations
