package TodoList;


/**
* TodoList/UserOperationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TodoList.idl
* Thursday, May 17, 2018 7:45:08 PM CST
*/

abstract public class UserOperationHelper
{
  private static String  _id = "IDL:TodoList/UserOperation:1.0";

  public static void insert (org.omg.CORBA.Any a, TodoList.UserOperation that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TodoList.UserOperation extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TodoList.UserOperationHelper.id (), "UserOperation");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TodoList.UserOperation read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_UserOperationStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TodoList.UserOperation value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TodoList.UserOperation narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TodoList.UserOperation)
      return (TodoList.UserOperation)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TodoList._UserOperationStub stub = new TodoList._UserOperationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TodoList.UserOperation unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TodoList.UserOperation)
      return (TodoList.UserOperation)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TodoList._UserOperationStub stub = new TodoList._UserOperationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
