
/**
* BulbBrokenExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LightBulb.idl
* Tuesday, May 8, 2018 2:41:36 PM CST
*/

public final class BulbBrokenExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public BulbBrokenException value = null;

  public BulbBrokenExceptionHolder ()
  {
  }

  public BulbBrokenExceptionHolder (BulbBrokenException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BulbBrokenExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BulbBrokenExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BulbBrokenExceptionHelper.type ();
  }

}
