
/**
* LightBulbPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LightBulb.idl
* Tuesday, May 8, 2018 2:41:36 PM CST
*/

public abstract class LightBulbPOA extends org.omg.PortableServer.Servant
 implements LightBulbOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("on", new java.lang.Integer (0));
    _methods.put ("off", new java.lang.Integer (1));
    _methods.put ("isOn", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // LightBulb/on
       {
         try {
           this.on ();
           out = $rh.createReply();
         } catch (BulbBrokenException $ex) {
           out = $rh.createExceptionReply ();
           BulbBrokenExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // LightBulb/off
       {
         this.off ();
         out = $rh.createReply();
         break;
       }

       case 2:  // LightBulb/isOn
       {
         try {
           boolean $result = false;
           $result = this.isOn ();
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (BulbBrokenException $ex) {
           out = $rh.createExceptionReply ();
           BulbBrokenExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:LightBulb:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public LightBulb _this() 
  {
    return LightBulbHelper.narrow(
    super._this_object());
  }

  public LightBulb _this(org.omg.CORBA.ORB orb) 
  {
    return LightBulbHelper.narrow(
    super._this_object(orb));
  }


} // class LightBulbPOA
