
/**
* LightBulbOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LightBulb.idl
* Tuesday, May 8, 2018 2:41:36 PM CST
*/

public interface LightBulbOperations 
{
  void on () throws BulbBrokenException;
  void off ();
  boolean isOn () throws BulbBrokenException;
} // interface LightBulbOperations
